### ISSUE TITLE
Rocker in CI/CD with Hive

### ISSUE THREAD

**Issue by nuest** [nuest/rockerverse-paper#71]
From https://twitter.com/mattmulvahill/status/1151256859208081408

![image](https://user-images.githubusercontent.com/1325054/73440451-96d25480-4351-11ea-9db3-550d21d5b932.png)

https://github.com/mmulvahill/r-tidyverse-java

@mmulvahill Is the a small story to tell about your usage of Rocker in CI/CD? What does the CI do?

Current paper draft at https://nuest.github.io/rockerverse-paper/master.pdf

**Comment by nuest** [comment]
@psolymos you also mention your use of Rocker in that thread: https://twitter.com/psolymos/status/1151323155085979648

Same question to you: are there some interesting lessons learned to tell as part of this collaborative paper? See https://nuest.github.io/rockerverse-paper/master.pdf

**Comment by psolymos** [comment]
@nuest thanks for checking in. I remember the tweet, and now I see that I am a bit late to the game (is there still a way to contribute?).

There are 2 primary use cases where I use Rocker images a lot (and Rocker is awesome, thanks for all the maintainers!):

(1) Rocker based or Rocker inspired images used as base image for Shiny apps deployed via Shinyproxy either on VMs or with a Kubernetes backend. Deployment also involves CI/CD pipelines in GitLab where package testing and build also used Rocker images. On success, this pipeline then triggers a webhook to deploy new images and restart services on the servers. I use GitLab's private registry to store our images.

(2) As I was looking more and more into decoupling UI logic from computations, I started looking into serverless options, very much along the lines of @MarkEdmondson1234 's great cloud run packages. I ended up writing an R template for [OpenFaaS](https://www.openfaas.com/) (https://github.com/analythium/openfaas-rstats-templates#readme). The nice thing about this project is that it comes with gateway API, monitoring, and supports Docker Swarm or Kubernetes with very sophisticated secrets handling. And it can be run on any system from Raspberry Pi to Azure AKS etc. 

There are 2 templates: one receives and sends JSON using STDIN/STDOUT. The second one uses {plumber} to serve the function in http mode. I also have examples of using OpenFaaS as a CORS enabled microservice. These are all built on top of `rocker/r-base`.

**Comment by MarkEdmondson1234** [comment]
Nice @psolymos ! I was looking at OpenFaaS as a non GCP option.

**Comment by nuest** [comment]
@psolymos Yes, contributions are still welcome, though they should be quite focused (= short ;-) ). If you have any particular lessons learned to share, I'm happy to help you find a good spot in the current manuscript for them.

- Your experiences with ShinyProxy could be an example when it is described
- If you have particular lessons learned, or also simple to complex examples, from using Rocker images in GitLab CI, those do fit well in the Development section
- The OpenFAAS template is definitely worth mentioning in the Deployment section!

_Would you be able to draft a PR before the end of next week?_

**Comment by psolymos** [comment]
Thanks @nuest , I'll get to it and send a PR.

**Comment by mmulvahill** [comment]
Hi @nuest -- thanks for following up on email.  I definitely missed the GH ping.

My use case was very simple.  Similar to @psolymos, we used Gitlab's CI pipeline to build & unit test our projects on every commit.  I added the java jdk, rJava, and RJDBC to a Rocker image since the focus of the package was creating a function for returning a JDBC connection to our Hadoop cluster. Later on we incorporated this package into our monorepo that contained Scala, Python, and R based projects and added it's build/test steps to the monorepo's larger CI pipeline . We weren't at the stage of using continuous deployment when I left a couple of months ago.  

I also used Rocker images as base images for spinning up my dev environment on our on-prem VM environment.  Nothing fancy, just start up the VM and use `docker run` to get started.  

I would love to contribute to the manuscript more thoroughly but am in the midst of a family relocation and starting a new job.  Let me know if you have any specific questions or if there's anything I contribute in the bit of time I have.

**Comment by nuest** [comment]
@mmulvahill Thanks for getting back. If you're keen on supporting the paper, you could take 20 mins. and check if the section "Development, debugging, and testing" covers the use case you describe. _Maybe you have a public URL that we could include as an illustrative example?_ What I see as an interesting bit I'd include as follows then:

> [Especially for long-running tests or complex system dependencies, these approaches to seperate installation of build dependencies with code testing streamline the development process.] Rocker containers can also streamline the integration of R software into larger CI pipelines, which might include multiple programming languages (cf. [URL HERE]).

@mmulvahill Regarding the dev environment in the VM: I though "nice idea, you can run a container in a corporate setting to have a controlled dev environment", but then stopped because if your IT lets you run Docker containers, you'd also be able to install RStudio locally, right?

@psolymos Looking forward to it!
